title: Eric Otto
description: Dynamic and highly motivated web developer with a passion for lifelong learning and data-driven applications. Enjoys working on products that allow users to improve their lives through insights gathered from data.
profile-pic: /images/profile.png
